import re
from dataclasses import dataclass
from app.guardrails.pii_detector import get_pii_detector
from app.retrieval.context_builder import BuiltContext
from app.utils.logger import logger


LEGAL_DISCLAIMER = (
    "\n\n---\n"
    "⚠️ **Disclaimer:** This response is generated by an AI research assistant "
    "and is intended for informational purposes only. It does not constitute "
    "legal advice. Always consult a qualified immigration attorney before "
    "making any legal decisions."
)


@dataclass
class SanitizedOutput:
    answer: str
    law_citations: list[str]
    case_citations: list[str]
    court_citations: list[str]
    pii_found_in_output: bool
    raw_answer: str


class OutputSanitizer:

    def __init__(self):
        self.pii_detector = get_pii_detector()

    def sanitize(
        self,
        raw_answer: str,
        context: BuiltContext,
    ) -> SanitizedOutput:

        logger.info("Sanitizing GPT output")

        pii_result = self.pii_detector.detect_and_redact(raw_answer)

        if pii_result.pii_found:
            logger.warning(
                f"PII detected in GPT output — "
                f"{len(pii_result.found_entities)} entities redacted"
            )

        clean_answer = pii_result.redacted_text

        clean_answer = re.sub(r'\bcertain\s+\[REDACTED-[A-Z_]+\]', 'certain applicants', clean_answer)
        clean_answer = re.sub(r'\beligible\s+\[REDACTED-[A-Z_]+\]', 'eligible applicants', clean_answer)
        clean_answer = re.sub(r'\bprove your\s+\[REDACTED-[A-Z_]+\]', 'prove your identity', clean_answer)
        clean_answer = re.sub(r'\bprove your the applicant\b', 'prove your identity', clean_answer)
        clean_answer = re.sub(r'\bthe\s+\[REDACTED-[A-Z_]+\]', 'the applicant', clean_answer)
        clean_answer = re.sub(r'\ban\s+\[REDACTED-[A-Z_]+\]', 'the applicant', clean_answer)
        clean_answer = re.sub(r'\ba\s+\[REDACTED-[A-Z_]+\]', 'the applicant', clean_answer)
        clean_answer = re.sub(r'\[REDACTED-[A-Z_]+\]', 'the applicant', clean_answer)

        clean_answer = re.sub(r'\[LAW\s+\d+\]', '', clean_answer)
        clean_answer = re.sub(r'\[CASE\s+\d+\]', '', clean_answer)
        clean_answer = re.sub(r'\[COURT\s+\d+\]', '', clean_answer)
        clean_answer = re.sub(r'\(LAW\s+\d+\)', '', clean_answer)
        clean_answer = re.sub(r'\(CASE\s+\d+\)', '', clean_answer)
        clean_answer = re.sub(r'\(COURT\s+\d+\)', '', clean_answer)
        clean_answer = re.sub(r',?\s*LAW\s+\d+', '', clean_answer)
        clean_answer = re.sub(r',?\s*CASE\s+\d+', '', clean_answer)
        clean_answer = re.sub(r',?\s*COURT\s+\d+', '', clean_answer)

        clean_answer = re.sub(r'\(\s*,\s*\)', '', clean_answer)
        clean_answer = re.sub(r'\(\s*\)', '', clean_answer)
        clean_answer = re.sub(r',\s*\)', ')', clean_answer)
        clean_answer = re.sub(r'\(\s*,', '(', clean_answer)
        clean_answer = re.sub(r'  +', ' ', clean_answer)
        clean_answer = re.sub(r' \.', '.', clean_answer)
        clean_answer = re.sub(r' ,', ',', clean_answer)

        law_citations = self._format_law_citations(context.law_references)
        case_citations = self._format_case_citations(context.case_references)
        court_citations = self._format_court_citations(
            getattr(context, 'court_case_references', [])
        )

        clean_answer += LEGAL_DISCLAIMER

        logger.info("Output sanitization complete")

        return SanitizedOutput(
            answer=clean_answer,
            law_citations=law_citations,
            case_citations=case_citations,
            court_citations=court_citations,
            pii_found_in_output=pii_result.pii_found,
            raw_answer=raw_answer,
        )

    def _format_law_citations(self, references: list[dict]) -> list[str]:
        citations = []
        seen = set()

        for ref in references:
            label = ref.get("label", "")
            if not label:
                if ref.get("visa_type"):
                    label = f"USCIS {ref['visa_type'].upper()} Policy Manual"
                else:
                    label = "USCIS Policy Manual"

            if label not in seen:
                seen.add(label)
                citations.append(label)

        return citations

    def _format_case_citations(self, references: list[dict]) -> list[str]:
        citations = []
        seen = set()

        for ref in references:
            label = ref.get("label", "")
            url = ref.get("url", "")

            if not label:
                label = f"Case Ref: {str(ref.get('chunk_id', ''))[:8]}..."

            # format as "label|url" so frontend can parse
            entry = f"{label}|{url}" if url else label

            if label not in seen:
                seen.add(label)
                citations.append(entry)

        return citations

    def _format_court_citations(self, references: list[dict]) -> list[str]:
        citations = []

        for ref in references:
            parts = []
            if ref.get("case_name"):
                parts.append(ref["case_name"])
            if ref.get("citation"):
                parts.append(ref["citation"])
            if ref.get("court"):
                parts.append(ref["court"])
            if ref.get("date"):
                parts.append(str(ref["date"])[:4])
            if parts:
                citations.append(" — ".join(parts))

        return citations