import type { Message } from "@/store/chatStore"

export function buildMemoMarkdown(messages: Message[], query?: string): string {
  const assistant = [...messages].reverse().find((m) => m.role === "assistant")
  const userQ = query || [...messages].reverse().find((m) => m.role === "user")?.content || ""

  if (!assistant) return ""

  const lines = [
    "# ImmigraAssist Research Memo",
    "",
    `**Date:** ${new Date().toLocaleDateString()}`,
    `**Query:** ${userQ}`,
    "",
    "## Answer",
    assistant.content,
    "",
  ]

  if (assistant.confidence_label) {
    lines.push(`**Confidence:** ${assistant.confidence_label}`, "")
  }

  if (assistant.cited_laws?.length) {
    lines.push("## Cited Laws", ...assistant.cited_laws.map((l) => `- ${l}`), "")
  }

  if (assistant.cited_cases?.length) {
    lines.push("## Cited Cases", ...assistant.cited_cases.map((c) => `- ${c}`), "")
  }

  if (assistant.court_cases?.length) {
    lines.push(
      "## Related Court Cases",
      ...assistant.court_cases.map(
        (c) => `- ${c.case_name} (${c.citation || c.court}) — ${c.courtlistener_url}`
      ),
      ""
    )
  }

  if (assistant.next_steps?.length) {
    lines.push("## Next Steps", ...assistant.next_steps.map((s) => `- ${s}`), "")
  }

  if (assistant.risks?.length) {
    lines.push("## Risks & Considerations", ...assistant.risks.map((r) => `- ${r}`), "")
  }

  if (assistant.related_forms?.length) {
    lines.push("## Related Forms", ...assistant.related_forms.map((f) => `- ${f}`), "")
  }

  lines.push(
    "---",
    "*This memo was generated by ImmigraAssist AI. Not legal advice — verify with a qualified attorney.*"
  )

  return lines.join("\n")
}

export function downloadMemo(messages: Message[], query?: string) {
  const md = buildMemoMarkdown(messages, query)
  const blob = new Blob([md], { type: "text/markdown" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = `immigraassist-memo-${Date.now()}.md`
  a.click()
  URL.revokeObjectURL(url)
}
